### ISSUE TITLE
"Edit content" Fenster leer

### ISSUE THREAD

**Issue by dive13** [terminal42/contao-rte_table#7]
Unter Contao 4.10 ist das Editieren nicht mehr möglich. Das Fenster bleibt leer. Eine Folge der neuen Version 5 vom TinyMCE?

**Comment by Kahmoon** [comment]
Jepp, ich habe eben das Selbe festgestellt. Scheint am TinyMCE 5 zu liegen.

Console:
`Refused to apply style from 'https://www.meinedomain.de/assets/tinymce4/js/skins/ui/contao/content.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

<a href="https://ibb.co/0rtJwwm"><img src="https://i.ibb.co/SBrvLL5/Bildschirmfoto-2020-10-06-um-08-32-42.png" alt="Bildschirmfoto-2020-10-06-um-08-32-42" border="0"></a>

**Comment by xprojects-de** [comment]
Kann ich bestätigen. Contao 4.12 und Contao 4.11
Gleicher JS-Fehler.

**Comment by aschempp** [comment]
könnt ihr prüfen ob der Fehler behoben ist wenn ihr die `dev-main as 1.0.8` über den Manager (oder composer.json) installiert?

**Comment by xprojects-de** [comment]
Morgen,

funktioniert super! Getestet unter 12.2.

Danke und Grüße

**Comment by aschempp** [comment]
@xprojects-de danke für's testen. Der Fehler ist behoben in Version 1.0.8
